== Versions

=== Channel description

[IMPORTANT]
====
There are several version types of ``Spacegate``, so please choose carefully when using them.

. ``ga`` General Availability, the official version, internally tested with no known bugs and verified in production, preferred for production environments!
. . ``rc`` Release Candidate, internally tested with no known bugs and available for production environments.
. ``beta`` Public Beta, no known major type of bugs, but minor type of bugs are allowed, production use requires careful evaluation!
. ``alpha`` Internal test version, very early test version, not internally tested, may have more Bugs, this version is similar to Technical Preview, must *not* be used in production environment!
. ``snapshot`` snapshot version, similar to Nightly version, frequent updates, no quality assurance, do *not* use for production environment!

====

TIP: The version number follows the https://semver.org/[``semver``] specification.

=== Release Notes

==== 0.1.0-alpha.2

- Initial release.
  The architecture is completed and basically available

==== 0.1.0-alpha.7

- Add several plugins: maintenance, status, compression,etc.
- Enhance SGPluginContext: optimize api, add more obtainable parameters.
- Code readability improvement and optimization.
- Write some documents.