// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginBinding } from "./PluginBinding";
import type { SgGateway } from "./SgGateway";
import type { SgRoute } from "./SgRoute";

export type ConfigItem<P = PluginBinding> = { gateway: SgGateway<P>, routes: { [key: string]: SgRoute<P> }, };