// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigItem } from "./ConfigItem";
import type { ObservabilityConfig } from "./ObservabilityConfig";
import type { PluginBinding } from "./PluginBinding";
import type { PluginInstanceMap } from "./PluginInstanceMap";

export type Config = { gateways: { [key: string]: ConfigItem<PluginBinding> }, plugins: PluginInstanceMap, api_port: number | null, observability: ObservabilityConfig, };