// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogConfig } from "./LogConfig";
import type { MetricConfig } from "./MetricConfig";
import type { OtlpProtocol } from "./OtlpProtocol";
import type { TraceConfig } from "./TraceConfig";

export type ObservabilityConfig = { enabled: boolean, service_name: string, otlp_endpoint: string, protocol: OtlpProtocol, traces: TraceConfig, metrics: MetricConfig, logs: LogConfig, };