// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PluginMetaData = { authors: string | null, description: string | null, version: string | null, homepage: string | null, repository: string | null, };