// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type PluginConfig = {
/**
 * 插件实例的管理端展示名称，不参与实例 ID 和运行时配置计算。
 */
display_name: string | null, spec: JsonValue, code: string, } & ({ "kind": "anon", uid: string, } | { "kind": "named",
/**
 * name should be unique within the plugin code, composed of alphanumeric characters and hyphens
 */
name: string, } | { "kind": "mono" });