// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginMetaData } from "./PluginMetaData";

export type PluginAttributes = { meta: PluginMetaData, mono: boolean, code: string, };