// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginConfig } from "./PluginConfig";

export type PluginInstanceMap = { map: { [key: string]: PluginConfig }, };