// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendHost } from "./BackendHost";
import type { PluginInstanceId } from "./PluginInstanceId";
import type { SgBackendProtocol } from "./SgBackendProtocol";

export type SgBackendRef<P = PluginInstanceId> = { host: BackendHost, 
/**
 * Port specifies the destination port number to use for this resource.
 */
port: number | null, 
/**
 * Timeout specifies the timeout for requests forwarded to the referenced backend.
 */
timeout_ms: number | null, protocol: SgBackendProtocol | null, 
/**
 * Weight specifies the proportion of requests forwarded to the referenced backend.
 * This is computed as weight/(sum of all weights in this BackendRefs list).
 * For non-zero values, there may be some epsilon from the exact proportion defined here depending on the precision an implementation supports.
 * Weight is not a percentage and the sum of weights does not need to equal 100.
 */
weight: number | null, 
/**
 * plugins define the filters that are applied to backend that match this hostnames.
 *
 * # Notice!
 * this field is ordered, the first plugin will be the outermost plugin.
 */
plugins: Array<P>, };