// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginBinding } from "./PluginBinding";
import type { SgListener } from "./SgListener";
import type { SgParameters } from "./SgParameters";

export type SgGateway<P = PluginBinding> = { name: string,
/**
 * Some parameters necessary for the gateway.
 */
parameters: SgParameters,
/**
 * Listeners associated with this Gateway. Listeners define logical endpoints that are bound on this Gateway’s addresses.
 */
listeners: Array<SgListener>,
/**
 * Filters define the filters that are applied to requests that match this gateway.
 */
plugins: Array<P>, };