// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgProtocolConfig } from "./SgProtocolConfig";

export type SgListener = { 
/**
 * Name is the name of the Listener. This name MUST be unique within a Gateway.
 */
name: string, 
/**
 * Ip bound to the Listener. Default is 0.0.0.0
 */
ip: string | null, 
/**
 * Port is the network port. Multiple listeners may use the same port, subject to the Listener compatibility rules.
 */
port: number, 
/**
 * Protocol specifies the network protocol this listener expects to receive.
 */
protocol: SgProtocolConfig, 
/**
 * `HostName` is used to define the host on which the listener accepts requests.
 */
hostname: string | null, };