// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpSessionAffinity } from "./McpSessionAffinity";
import type { PluginBinding } from "./PluginBinding";
import type { SgBackendRef } from "./SgBackendRef";
import type { SgMcpLegacySse } from "./SgMcpLegacySse";
import type { SgMcpTransport } from "./SgMcpTransport";
import type { SgRouteKind } from "./SgRouteKind";
import type { TimeoutMode } from "./TimeoutMode";

export type SgMcpRoute<P = PluginBinding> = { kind: SgRouteKind, route_name: string, hostnames: Array<string> | null, transport: SgMcpTransport, path: string, legacy_sse: SgMcpLegacySse | null, backends: Array<SgBackendRef<P>>, plugins: Array<P>, timeout_mode: TimeoutMode, session_affinity: McpSessionAffinity, };