// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObservabilityConfig } from "./ObservabilityConfig";

export type SgParameters = {
/**
 * Redis access Url, Url with permission information.
 */
redis_url: string | null,
/**
 * Maximum number of Redis connections this gateway may borrow concurrently.
 */
redis_pool_max_size: number | null,
/**
 * Maximum time in milliseconds to wait for an available Redis connection.
 */
redis_pool_wait_timeout_ms: number | null,
/**
 * Maximum time in milliseconds to establish a Redis connection.
 */
redis_pool_create_timeout_ms: number | null,
/**
 * Maximum time in milliseconds to validate a Redis connection before reuse.
 */
redis_pool_recycle_timeout_ms: number | null,
/**
 * Gateway Log_Level
 */
log_level: string | null,
/**
 * Gateway language
 */
lang: string | null,
/**
 * Ignore backend tls verification
 */
ignore_tls_verification: boolean | null,
/**
 * Add request id for every request
 */
enable_x_request_id: boolean | null, observability: ObservabilityConfig, };
