// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SgParameters = { 
/**
 * Redis access Url, Url with permission information.
 */
redis_url: string | null, 
/**
 * Gateway Log_Level
 */
log_level: string | null, 
/**
 * Gateway language
 */
lang: string | null, 
/**
 * Ignore backend tls verification
 */
ignore_tls_verification: boolean | null, 
/**
 * Add request id for every request
 */
enable_x_request_id: boolean | null, };