// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginBinding } from "./PluginBinding";
import type { SgHttpRoute } from "./SgHttpRoute";
import type { SgMcpRoute } from "./SgMcpRoute";

export type SgRoute<P = PluginBinding> = SgMcpRoute<P> | SgHttpRoute<P>;