apiVersion: spacegate.idealworld.group/v1
kind: SgFilter
metadata:
  name: filters
spec:
  filters:
    - code: limit
      config:
        max_request_number: 10
  targetRefs:
    - kind: gateway
      name: echo
