[env]
TS_RS_EXPORT_DIR = { value = "./sdk/admin-client/src/model", relative = true }
CONFIG = "file:resource/install/default-config"
PLUGINS = "./target/debug"
RUST_LOG = "trace"
FORMAT = "json"
KEY = "moCZihByqvXt4dfMYjOz75fzBi0eul6Ffg2EoUzWyqA="
SK = "password"