const fs = require('fs');
const path = require('path');
const projectRoot = path.resolve(__dirname, '..');
const directoryPath = path.join(projectRoot, 'src/model');
const indexPath = path.join(directoryPath, 'index.ts');


fs.readdir(directoryPath, (err, files) => {
    if (err) {
        return console.error('Unable to scan directory: ' + err);
    }

    let exports = '// @generated by script.\n';
    files.forEach((file) => {
        if (file !== 'index.ts' && file.endsWith('.ts')) {
            const moduleName = file.replace('.ts', '');
            exports += `export * from './${moduleName}';\n`;
        }
    });

    fs.writeFile(indexPath, exports, (err) => {
        if (err) {
            return console.error('Unable to write file: ' + err);
        }
    });
});