// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigItem } from "./ConfigItem";
import type { PluginInstanceId } from "./PluginInstanceId";

export type Config = { gateways: { [key: string]: ConfigItem<PluginInstanceId> }, plugins: Record<string, PluginConfig>, };