// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigItem } from "./ConfigItem";

export interface Config { gateways: Record<string, ConfigItem>, }