// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstanceId } from "./PluginInstanceId";
import type { SgGateway } from "./SgGateway";
import type { SgHttpRoute } from "./SgHttpRoute";

export type ConfigItem<P = PluginInstanceId> = { gateway: SgGateway<P>, routes: { [key: string]: SgHttpRoute<P> }, };