// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgGateway } from "./SgGateway";
import type { SgHttpRoute } from "./SgHttpRoute";

export interface ConfigItem { gateway: SgGateway, routes: Record<string, SgHttpRoute>, }