// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendHost } from "./BackendHost";
import type { SgBackendProtocol } from "./SgBackendProtocol";
import type { SgRouteFilter } from "./SgRouteFilter";

export interface SgBackendRef { host: BackendHost, port: number, timeout_ms: number | null, protocol: SgBackendProtocol | null, weight: number, filters: Array<SgRouteFilter>, }