// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgListener } from "./SgListener";
import type { SgParameters } from "./SgParameters";
import type { SgRouteFilter } from "./SgRouteFilter";

export interface SgGateway { name: string, parameters: SgParameters, listeners: Array<SgListener>, filters: Array<SgRouteFilter>, }