// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SgHttpPathMatch = { "kind": "Exact", "value": string } | { "kind": "Prefix", "value": string } | { "kind": "Regular", "value": string };