// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgBackendRef } from "./SgBackendRef";
import type { SgHttpRouteMatch } from "./SgHttpRouteMatch";
import type { SgRouteFilter } from "./SgRouteFilter";

export interface SgHttpRouteRule { matches: Array<SgHttpRouteMatch> | null, filters: Array<SgRouteFilter>, backends: Array<SgBackendRef>, timeout_ms: number | null, }