// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgHttpRouteRule } from "./SgHttpRouteRule";
import type { SgRouteFilter } from "./SgRouteFilter";

export interface SgHttpRoute { gateway_name: string, hostnames: Array<string> | null, filters: Array<SgRouteFilter>, rules: Array<SgHttpRouteRule>, priority: number, }