// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgHttpHeaderMatch } from "./SgHttpHeaderMatch";
import type { SgHttpMethodMatch } from "./SgHttpMethodMatch";
import type { SgHttpPathMatch } from "./SgHttpPathMatch";
import type { SgHttpQueryMatch } from "./SgHttpQueryMatch";

export interface SgHttpRouteMatch { path: SgHttpPathMatch | null, header: Array<SgHttpHeaderMatch> | null, query: Array<SgHttpQueryMatch> | null, method: Array<SgHttpMethodMatch> | null, }