// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgProtocolConfig } from "./SgProtocolConfig";

export interface SgListener { name: string, ip: string | null, port: number, protocol: SgProtocolConfig, hostname: string | null, }