// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SgParameters { redis_url: string | null, log_level: string | null, lang: string | null, ignore_tls_verification: boolean | null, }