// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SgTlsConfig } from "./SgTlsConfig";

export type SgProtocolConfig = { "type": "http" } | { "type": "https", tls: SgTlsConfig, };